### ISSUE TITLE
How to update API KEY?

### ISSUE THREAD

**Issue by xryv** [kristoferlund/duet-gpt#3]

**Comment by kristoferlund** [comment]
@xryv good question. I haven't implemented that yet. 

## Short term solution 

Edit `~/.duet-gpt`.

## Better solution

Make it possible to access a "settings" interface in duet-gpt. 

Suggestion: `duet-gpt config` allows you to change settings. 

Actually, this is a great feature to let duet-gpt try to build, want to have a go at it?

**Comment by kristoferlund** [comment]
@xryv This issue is solved in new version
